apiVersion: v1
kind: Service
metadata:
  name: myntra-service
  labels:
    app: myntra-deployment
spec:
  selector:
    app: myntra-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
