#GitHub Actions using runner
name: CI/CD

# Exclude the workflow on the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'myntra-clone-chart/**'
      - 'k8s/**'
      - 'EKS-TF/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up node js 14
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Build
        run: npm run build

  push:
    runs-on: ubuntu-latest
    need: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myntra:${{ github.run_id }}

 update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' myntra-clone-chart/values.yml

      - name: Commit and push changes
        run: |
          git config --global user.email "goutham@gmail.com"
          git config --global user.name "goutham"
          git add myntra-clone-chart/values.yml
          git commit -m "Update tag in helm chart"
          git push
